name: alecsibilia
favicon: null
layout_spectrum: 0.5519349877722561
typography_spectrum: 0.34478463791310787
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.17884030216373503
  lightness: 0.9116853585001081
  saturation: 0.21740617230534554
  rhythmicContrast: 0.6576364859938622
purpose: []
