layout_spectrum: 0.43333200234661595
typography_spectrum: 0.5211776465009714
color:
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
  brandStrength: 0.6810944993308939
  lightness: 0.12159051166478507
  saturation: 0.17905872425433286
  rhythmicContrast: 0.00890418411795013
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Alec Sibilia
  email: sibilia.alec@gmail.com
name: alecsibilia
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Dribbble
    url: 'https://dribbble.com/amsibilia'
    type: external
favicon: null
title: Make Products That Matter.
content: []
description: Alec Sibilia - Product / UX Designer & Developer
purpose:
  - type: contact
    url: 'mailto:sibilia.alec@gmail.com'
    label: Let's Chat
